name: Build docker image

on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build_zabbix_server:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v6
        with:
          registry: ghcr.io
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
          repository: dark-vex/zabbix-server-mysql
          tags: latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.1

      - name: Sign image
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/dark-vex/zabbix-server-mysql:latest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
