name: Build docker image

on:
  workflow_dispatch:  
  push:
    branches: [ "main" ]
    paths:
      - 'release-versions/*'
      - Dockerfile
      - requirements.txt

jobs:
  build_zabbix_server:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
          registry: ghcr.io

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dark-vex/zabbix-server-mysql:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.9.1

      - name: Sign image
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ghcr.io/dark-vex/zabbix-server-mysql:latest
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
