name: Get latest release version
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/zabbix/zabbix-docker/releases |grep '\"tag_name\": \"5.0.*\"' | \
          awk '{print $2}' | \
          head -1 | \
          tr -d '",' > release-versions/zabbix-server-5.0-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'test'
          git config --global user.email 'test@users.noreply.github.com'
          git commit -am "New release version"
          git push
