# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build, scan, push and upload sarif report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 23 * * 1'

permissions:
  contents: read

jobs:

  build:

    permissions:
      checks: write # for sysdiglabs/scan-action to publish the checks
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      # Tag image to be built
      # Change ${{ github.repository }} variable by another image name if you want but don't forget changing also image-tag below
      run: docker build . --file Dockerfile --tag ghcr.io/dark-vex/zabbix-server-mysql:latest

    - name: Image Scan
      id: scan
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: |
        curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
        chmod +x wizcli
        ./wizcli scan container-image ghcr.io/dark-vex/zabbix-server-mysql:latest --by-policy-hits=DISABLED --sarif-output-file=sarif.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v4
      #Upload SARIF file
      if: success() || failure()
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
